✨ 添加AI视频总结
FloatTech/AnimeAPI pull request #41
Opened 2023-10-11 16:39 UTC by guohuiyuan

2023-10-11 16:51 UTC, fumiama requested changes
这是莲宝写的代码吧，我是真不想看啊，血压又高了。之前群里给他说的是一点没改啊。

2023-10-11 16:51 UTC, fumiama commented on .gitignore
> +*.json
要是有人要加json咋办，建议将这个ignore声明移动到bilibili文件夹

2023-10-11 16:51 UTC, fumiama commented on bilibili/wbi.go
> +	newUrlStr := urlObj.String()
看看warn

2023-10-11 16:51 UTC, fumiama commented on bilibili/wbi.go
> +	hash := md5.Sum([]byte(queryStr + mixinKey))
我有印象，这不是莲宝写的我让他改吗，改成在源头h.Write()

2023-10-11 16:51 UTC, fumiama commented on bilibili/wbi.go
> +	json := string(body)
这啥

2023-10-11 16:51 UTC, fumiama commented on bilibili/wbi.go
> +		if v < len(orig) {
大于直接return啊

2023-10-11 16:51 UTC, fumiama commented on bilibili/wbi.go
> +	return str.String()[:32]
等着panic？

2023-10-11 16:51 UTC, fumiama commented on bilibili/wbi.go
> +		fmt.Printf("Error: %s", err)
这啥

2023-10-11 16:51 UTC, fumiama commented on bilibili/wbi.go
> +		fmt.Printf("Error: %s", err)
这又是啥

2023-10-11 16:56 UTC, guohuiyuan commented
> 这是莲宝写的代码吧，我是真不想看啊，血压又高了。之前群里给他说的是一点没改啊。

不是着那个https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md 里面的代码。。

2023-10-12 15:07 UTC, fumiama approved these changes

2023-10-12 15:07 UTC, merged