fix:修改mockingbird类，增加新模型
FloatTech/AnimeAPI pull request #5
Opened 2022-02-21 05:13 UTC by guohuiyuan

2022-02-21 09:14 UTC, fumiama requested changes

2022-02-21 09:14 UTC, fumiama commented on tts/mockingbird/mocking_bird.go
> +	modeMap     = func() (m map[string]*MockingBirdTTS) {
建议统一放到上层的aireply，不然抽象没有意义

2022-02-21 09:14 UTC, fumiama commented on tts/mockingbird/mocking_bird.go
> +	azfile          = dbpath + "az.wav"
改名会导致之前所有版本无法正常下载

2022-02-21 09:14 UTC, fumiama commented on tts/mockingbird/mocking_bird.go
> +func NewMockingBirdTTS(mode string) *MockingBirdTTS {
新建的时候，根据mode直接返回新结构体即可

2022-02-21 09:27 UTC, guohuiyuan commented on tts/mockingbird/mocking_bird.go
> +	azfile          = dbpath + "az.wav"
用新的名字，旧的文件也保存

2022-02-21 09:28 UTC, guohuiyuan commented on tts/mockingbird/mocking_bird.go
> +	modeMap     = func() (m map[string]*MockingBirdTTS) {
问题来了，我是学的你aireply写的😂

2022-02-21 14:37 UTC, fumiama commented on tts/mockingbird/mocking_bird.go
> +func (tts *MockingBirdTTS) String() string {
同理，建议恢复New，所需参数都可以在入参指定，还能加注释。

2022-02-21 14:38 UTC, fumiama commented on tts/tts.go
> +	modeMap = func() (m map[string]TTS) {
同理，不建议有这个map，只要实现了 TTS interface 都应当视作 tts，这样也好扩展。

2022-02-21 14:39 UTC, fumiama commented on tts/tts.go
> +	String() string
这个可以保留

2022-02-21 14:39 UTC, fumiama commented on tts/mockingbird/mocking_bird.go
> +	Vocoder         int
不建议改成public，其他改动同理。

2022-02-21 14:40 UTC, fumiama commented on tts/baidutts/baidutts.go
> -func NewBaiduTTS(per int) *BaiduTTS {
不好，这样用户根本不知道目前有哪些tts了，建议恢复原来的特事特办。

2022-02-21 14:40 UTC, fumiama commented on tts/baidutts/baidutts.go
> +func (tts *BaiduTTS) String() string {
这个接口函数可以保留

2022-02-21 14:41 UTC, fumiama commented on tts/tts.go
> +func NewTTS(mode string) TTS {
不建议加这个。aireply是因为名字好记，参考`image/xxx`系列的Register，但是对于这种难以记住的排列组合，建议特事特办，由用户自己New想要的。

2022-02-21 14:43 UTC, fumiama commented on tts/mockingbird/mocking_bird.go
> +	modeMap     = func() (m map[string]*MockingBirdTTS) {
别学那个😂

2022-02-21 14:49 UTC, guohuiyuan commented on tts/tts.go
> +func NewTTS(mode string) TTS {
那为什么要tts这个包，好像也没用啊

2022-02-21 15:06 UTC, fumiama commented on tts/tts.go
> +func NewTTS(mode string) TTS {
这是给前端用的，只需要写一个TTS.Speak()，代码就不用动了，换的只是接口底下的实现而已。

2022-02-21 15:09 UTC, fumiama commented on tts/tts.go
> +func NewTTS(mode string) TTS {
比如
```go
var tts TTS

zero.Onxxx("设置A") {
    tts = NewA(具体参数)
}

zero.Onxxx("设置B") {
    tts = NewB(具体参数1, 具体参数2)
}

zero.Onxxx("Speakxxx") {
    ctx.Send(tts.Speak(xxx))
}
```

2022-02-22 04:24 UTC, fumiama approved these changes

2022-02-22 04:24 UTC, merged