[Feat] Add more API from lolimi, excepts C4o
FloatTech/AnimeAPI pull request #56
Opened 2024-08-21 13:35 UTC by EatHatsuneShallots

不太清楚要怎么命名
C4o: https://apii.lolimi.cn/doc/13
Closes #54

2024-08-21 15:18 UTC, fumiama requested changes
既然旧版已经不可用，你就直接在旧版上改，不要新增文件和结构体。至于错误，就调试正确之后再提交吧，注释交上来也没人看没人用。

2024-08-22 07:16 UTC, EatHatsuneShallots commented
> 至于错误，就调试正确之后再提交吧

目测 `请使用psot格式请求如有疑问进官方群` 应该是我滥用了 API （或者是 API 本身）的问题，代码应该没有问题
因为官网的示例代码运行也是这样

2024-08-22 13:36 UTC, fumiama requested changes

2024-08-22 13:36 UTC, fumiama commented on aireply/lolimi.go
> +func NewLolimiMemoryAi(u, name string, key string, limit int, banwords ...string) *LolimiMemoryAi {
既然入参相同，可以整合为一个，新增一个参数`memory bool`决定是否使用记忆。

2024-08-22 14:10 UTC, EatHatsuneShallots commented on aireply/lolimi.go
> +func NewLolimiMemoryAi(u, name string, key string, limit int, banwords ...string) *LolimiMemoryAi {
入参函数个人认为不太建议合并，因为会让开发者不好分辨是什么类型的 AI。不过结构体倒是可以合并

2024-08-22 14:54 UTC, fumiama approved these changes

2024-08-22 14:54 UTC, merged