🎨 使用公有http方法
FloatTech/AnimeAPI pull request #9
Opened 2022-05-11 03:14 UTC by guohuiyuan

2022-05-11 05:02 UTC, fumiama requested changes

2022-05-11 05:02 UTC, fumiama commented on tts/baidutts/baidutts.go
> +		err = errors.New(binary.BytesToString(data))
这是什么意思

2022-05-11 05:02 UTC, fumiama commented on tts/mockingbird/mocking_bird.go
> +		_, err := file.GetLazyData(azfile, false)
false不会影响后续处理吗

2022-05-11 13:16 UTC, guohuiyuan commented on tts/baidutts/baidutts.go
> +		err = errors.New(binary.BytesToString(data))
就是正常的话不是一个json格式的数据，是一个音频，非正常的话就是json格式，目前已经白嫖不了别人的key了

2022-05-11 13:17 UTC, guohuiyuan commented on tts/mockingbird/mocking_bird.go
> +		_, err := file.GetLazyData(azfile, false)
为了自定义音频，这音频不应该强相等的

2022-05-11 16:23 UTC, fumiama commented on tts/baidutts/baidutts.go
> +		err = errors.New(binary.BytesToString(data))
可否把这个json中的某个字段提取为报错而不是全部

2022-05-11 16:23 UTC, fumiama commented on tts/mockingbird/mocking_bird.go
> +		_, err := file.GetLazyData(azfile, false)
自定义之后可以达到什么效果呢，模型是一样的啊

2022-05-11 16:28 UTC, guohuiyuan commented on tts/baidutts/baidutts.go
> +		err = errors.New(binary.BytesToString(data))
> 可否把这个json中的某个字段提取为报错而不是全部

类型不知道有多少种

2022-05-11 16:38 UTC, fumiama commented
> 示例音频会影响合成效果，示例音频语速快的，合成的语速也快，这个音频，应该找到效果最好的去用

好吧，不过我觉得大部分人都不知道怎么替换就是了😂

2022-05-12 03:17 UTC, fumiama approved these changes

2022-05-12 03:17 UTC, merged